<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="stylesheet" href="/css/style.css" type="text/css" media="screen, projection" />
</head>
<body id="body" height="800" style="height: 800px; overflow-y:scroll;">
<!--<?php print_r($this->debugParams) ?>-->
    <div>
        <img class="img_congratulation" src="/img/ded_moroz.jpg" alt="">
        <div class="congratulation">
            <p>Вітаємо! Ваше повідомлення поставленно до черги. Як тільки Дід Мороз його прочитає він одразу доставить його на стіну вашому другу.</p>
            <a href="/index">ІЩЕ!</a>
        </div>
    </div>
</body>
</html>