<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <link rel="stylesheet" href="/css/style.css" type="text/css" media="screen, projection" />
        <script type="text/javascript" src="/js/jquery.min.js" ></script>
        <script type="text/javascript" src="/js/jcarousellite_1.0.1.min.js" ></script>

        <script type="text/javascript" src="/js/jquery.lightbox-0.5.js" ></script>
        <script type="text/javascript" src="/js/bootstrap.js" ></script>

        <link rel="stylesheet" href="/css/jquery.lightbox-0.5.css" type="text/css" media="screen, projection" />
        <link rel="stylesheet" href="/css/bootstrap.css" type="text/css" media="screen, projection" />
        <link href='http://fonts.googleapis.com/css?family=Marck+Script&subset=cyrillic,latin' rel='stylesheet' type='text/css'>
        <script src="http://vkontakte.ru/js/api/xd_connection.js?2" type="text/javascript"></script>
        <script type="text/javascript">
         WebFontConfig = {
             google: { families: [ 'Marck+Script::latin,cyrillic' ] }
         };
         (function() {
             var wf = document.createElement('script');
              wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
               '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
              wf.type = 'text/javascript';
                wf.async = 'true';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(wf, s);
            })();
        </script>
        <script type="text/javascript">
            $(document).ready(function() {
            // thumb-carousel
             $(".thumb-carousel").jCarouselLite({
                btnNext: ".thumb-center .next",
                btnPrev: ".thumb-center .prev",
                visible: 1,
                circular: false
             });

            });
            VK.init(function() {
                // API initialization succeeded
                // Your code here
            });
            VK.callMethod("resizeWindow", 680, 890);
            function post_photo(photo_id){
                    //alert("<?=$this->currentUserId?>");
                //VK.callMethod("resizeWindow", 680, 890);
                    VK.api("wall.savePost",{
                    'wall_id':"<?=$this->currentUserId?>",
                    'post_id':'tszafs21123t',
                    'message':'Хочу настоящую Валентинку, а не на стенку http://vk.com/app2711477',
                    'photo_id':photo_id
                }, function(data) { VK.callMethod("saveWallPost", data.response.post_hash); });

            }


    </script>
        <script type="text/javascript">
        
            $(document).ready(function() {
                   $('#gallery a').lightBox( {
                       maxHeight: 300, maxWidth: 300,
                       imageBtnClose: '/images/lightbox-btn-close.gif',
                       imageBlank: '/images/lightbox-blank.gif',
                       imageLoading: '/images/lightbox-ico-loading.gif',
                       imageBtnPrev:'/images/lightbox-btn-prev.gif',			// (string) Path and the name of the prev button image
			           imageBtnNext:'/images/lightbox-btn-next.gif'
                   });
                $('.img_block').hover(function() {
	            	var imgBlock = $(this);
		                imgBlock.find('.view').show();

                },function() {
                	var imgBlock = $(this);
    	            imgBlock.find('.view').hide();

                });
            });

        </script>
</head>
<body id="body">
<!--<?php print_r($this->debugParams) ?>-->
    <div id="wrapper">
        <div class="empty">Служба св. Валентина</div>
        <div class="menu">
           <a href="/index/images?group=1" class="btn">Открытки</a>
           <a href="/index/images?group=2" class="btn">Hand-made</a>
           <a href="/index/myvalentines" class="btn">Мои валентинки</a>
            <a href="/index/about" class="btn">О проекте</a>
        </div>
        <div class="thumb-left"><div class="thumb-right"><div class="thumb-center">
            <a href="javascript:void(0);" class="prev disabled" ><img src="/img/prev.png" alt=""></a>
            <div class="thumb-carousel">
               <ul>
                <?
                  $images = $this->images;
                  for ($i = 0; $i <= count($images)-1; $i = $i+9) {
                ?>
                <li>
                    <?php for ($j = $i; $j <= $i+8; $j++){
                              if(isset($images[$j])){
                    ?>

                    <div class="img_block">
                        <div class="img_inside" >
                            <!--a href="/images/<?php echo basename($images[$j]['src'],"?")?>" rel="lightbox">1111<img src="/images/<?php echo basename($images[$j]['src'],"?")?>" style="display:none;"/></a-->
                           <a class="view_want"  href="javascript:void(0);" onclick="return post_photo('<?if(!empty($images[$j]['photo_id'])){ echo $images[$j]['photo_id'];}else{echo '161804409_277659693';}?>');">Хочу</a>
                            <a class="view"  href="/index/address?image_id=<?php echo $images[$j]['image_id']?>">Заказать</a>
                            <span class="view_price">Цена: <?php echo $images[$j]['price']?> грн.</span>
                            <div id="gallery"><a title="<?php echo $images[$j]['title']?>" href="/images/<?php echo basename($images[$j]['src'],"?")?>" ><img src="/images/<?php echo basename($images[$j]['src'],"?")?>"/></a></div>
                             
                        </div>
                        <div class="send">
                            Отправок:  <?php echo $images[$j]['sent_count']?>
                        </div>
                    </div>
                <?php } }?>
                 </li>
                 <? } ?>
                    
              </ul>
            </div>
               <a href="javascript:void(0);" class="next disabled" ><img src="/img/next.png" alt=""></a>
        </div></div></div><!-- .thumb-left -->
 <div class="footer"><img src="/img/footer.png" alt=""></div>
    </div>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28937815-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>
</html>