<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="stylesheet" href="/css/style.css" type="text/css" media="screen, projection" />
<script type="text/javascript" src="/js/jquery.min.js" ></script>
<script src="http://vkontakte.ru/js/api/xd_connection.js?2" type="text/javascript"></script>
<script type="text/javascript">
    VK.init(function() {

     // API initialization succeeded
     // Your code here
    });
    VK.callMethod("resizeWindow", 680, 1800);
    </script>
</head>
<body id="body">
    <div id="wrapper">
        <div class="empty"></div>
        <div class="menu">
            <a href="/index/friends">Ідемо далі</a>
            <a href="/admin">Админ</a>
            <!-- Ця строчка снімає голоса із юзера і зачісляє на рахунок юзера в додатку.
            Потім нада перевести ці голоса із рахунка юзера в додатку на рахунок самого додатку-->
            <a href="#" onclick="VK.callMethod('showPaymentBox', 2);">Pay</a>
        </div>
        <div class="phot_main">
            <?php foreach ($this->images as $image){?>
                <div class="img_block">
                    <div class="img_inside">
                        <a href="/index/friends?image_id=<?php echo $image['image_id']?>"><img src="/img/<?php echo basename($image['src'],"?")?>"/></a>
                        <?php if (!empty($image['price'])){?>
                            <div class="img_price"><?php echo $image['price']?></div>
                        <?php }?>
                    </div>
                    <div class="send">
                        Отправок:<?php echo $image['sent_count']?>
                    </div>
                </div>
            <?php }?>
        </div>

    </div>
</body>
</html>