<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <script src="http://vkontakte.ru/js/api/xd_connection.js?2" type="text/javascript"></script>
<script type="text/javascript">
    VK.init(function() {

     // API initialization succeeded
     // Your code here
    });
    function call(id,message,photo_id)
    {

	    VK.api("wall.savePost", {"wall_id":id,"photo_id":photo_id,"message": message,"test_mode": 1},function(data){
        //            alert(data.response.post_hash);
					VK.callMethod("saveWallPost", data.response.post_hash);
        });

    }

  </script>
</head>
<body>
<br /><br />
<div id="view-content">

	<p>View script for controller <b>Admin</b> and script/action name <b>index</b></p>
    <table>
        <? foreach($this->messages as $messages):?>
            <tr>
                <td><?=$messages['message_sent_to']?> </td>
                <td>
                    <a href="javascript:call(<? echo '\''.$messages['message_sent_to'].'\',\''.$messages['message'].'\',\''.$messages['photo_id'].'\''?>);">Send</a>


                </td>
            </tr>
        <? endforeach;?>
        </table>

   <? print_r($this->messages);die;?>
</div>
</body>
</html>